version: 2.1

description: |
  Simplify common tasks for building and testing Gradle projects

examples:
  gradle-workflow:
    description: Checkout, build, and test a Gradle project

    usage:
      version: 2.1

      orbs:
        gradle: circleci/gradle@1.0.0

      workflows:
        checkout-build-test:
          jobs:
            - gradle/test:
                test_command: test

  custom_executor:
    description: |
      If you want to override the executor used by default.

    usage:
      version: 2.1

      orbs:
        gradle: circleci/gradle@1.0.0

      executors:
        my-executor:
          docker:
            - image: circleci/openjdk:11

      workflows:
        gradle_test:
          jobs:
            - gradle/test:
                executor: my-executor

executors:
  gradle:
    description: The docker container to use when running Gradle builds
    docker:
      - image: circleci/openjdk:8-jdk-node
    environment:
      # Disable fancy terminal updates
      TERM: dumb

commands:
  with_cache:
    description: |
      Run a set of steps with gradle dependencies cached.

      This command will first restore a cache of gradle dependencies, if one was
      saved by a previous build. The provided `steps` will then be executed, and
      if successful, then a fresh cache will be saved, if required.

      The contents of the `~/.gradle` directory is cached, which will substantially
      improve build times for projects with many dependencies.

      The cache-key is generated from any files named `build.gradle` that are
      present in the `working_directory`.
    parameters:
      steps:
        type: steps
    steps:
      - run:
          name: Generate Cache Checksum
          command: find . -name 'build.gradle' -exec cat {} + | shasum | awk '{print $1}' > /tmp/gradle_cache_seed
      - restore_cache:
          key: gradle-{{ checksum "/tmp/gradle_cache_seed" }}
      - steps: << parameters.steps >>
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "/tmp/gradle_cache_seed" }}

jobs:
  test:
    description: |
      Checkout, build and test a gradle project.
    executor: <<parameters.executor>>
    parameters:
      executor:
        description: The name of custom executor to use
        type: executor
        default: gradle
      test_command:
        type: string
        default: test
    steps:
      - checkout
      - with_cache:
          steps:
            - run:
                name: Run Tests
                command: ./gradlew << parameters.test_command >>
