version: 2.1

description: |
  A set of commands and jobs for working with the Rollbar API

examples:
 deploy_notification:
  description: Use the Rollbar orb to send a notification that a project has been deployed
  usage:
    version: 2.1

    orbs:
      rollbar: circleci/rollbar@1.0.0

    workflows:
      deploy_application:
        jobs:
          - rollbar/notify_deploy

commands:
  notify_deploy:
    description: |
      A step to notify Rollbar the project has been deployed.
      Add this as the last step of your the job that you
      use to deploy.
    parameters:
      project_environment:
        type: string
        default: production
        description: The Rollbar environment. Defaults to production.
      rollbar_token:
        type: env_var_name
        description: name of your Rollbar API token environment variable
        default: ROLLBAR_ACCESS_TOKEN
    steps:
      - run:
          name: Notify Rollbar
          command: |
            curl https://api.rollbar.com/api/1/deploy/ \
              --form access_token=<<parameters.rollbar_token>> \
              --form environment=<<parameters.project_environment>> \
              --form revision=$CIRCLE_SHA1 \
              --form local_username=$CIRCLE_USERNAME

jobs:
  notify_deploy:
    description: |
      A job to notify Rollbar the project has been deployed.
    parameters:
      project_environment:
        type: string
        default: production
        description: The Rollbar environment. Defaults to production.
      rollbar_token:
        type: env_var_name
        description: name of your Rollbar API token environment variable
        default: ROLLBAR_ACCESS_TOKEN
    docker:
      - image: circleci/buildpack-deps:18.04-scm
    steps:
      - notify_deploy:
          project_environment: <<parameters.project_environment>>
          rollbar_token: <<parameters.rollbar_token>>
